# Generated by Django 5.2.17 on 2026-08-18 13:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=core.models.new_id, max_length=64, primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=64)),
                ('record_id', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=core.models.new_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('managing_partner', 'Managing Partner'), ('lawyer', 'Lawyer'), ('clerk', 'Clerk'), ('accountant', 'Accountant')], default='lawyer', max_length=32)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('auth_token', models.CharField(default=core.models.new_id, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenericRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=64)),
                ('record_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['table', 'updated_at'], name='core_generi_table_fd3e80_idx')],
                'constraints': [models.UniqueConstraint(fields=('table', 'record_id'), name='unique_table_record')],
            },
        ),
    ]
